file(TO_NATIVE_PATH "${ProcessLocation}" ProcessLocation)
string(REPLACE "\\" "\\\\" ProcessLocation "${ProcessLocation}")
get_filename_component(Guard2 ${OutputFile} NAME_WE)
get_filename_component(OutputFilePath ${OutputFile} PATH)
get_filename_component(Guard1 ${OutputFilePath} NAME_WE)
get_filename_component(OutputFilePath ${OutputFilePath} PATH)
get_filename_component(Guard0 ${OutputFilePath} NAME_WE)
string(TOUPPER "${Guard0}_${Guard1}_${Guard2}_H_" Guard)
configure_file(${InputFile} ${OutputFile} @ONLY)
